version: '3'

services:
  web:
    container_name: laravel_web
    build:
      context: .
    ports:
      - 9004:80

    depends_on:
      - db
  db:
    container_name: laravel_db
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD=secret
      MYSQL_DATABASE=yourdb
  phpmyadmin:
    image: 2034/phpmyadmin
    container_name: laravel_phpmyadmin
    depends_on:
      - db
    ports:
      - 9005:80
    environment:
       MYSQL_PASSWORD: secret
       MYSQL_ROOT_PASSWORD: secret
